checkpoint: outputs/training/py_cudasift_finetune+lg_MD_continue_V2/checkpoint_best.tar
model:
    name: two_view_pipeline
    extractor:
        name: extractors.sift
        backend: py_cudasift
        max_num_keypoints: 4096
        force_num_keypoints: False
        nms_radius: 0
        trainable: False
        detection_threshold: 0.4  # 1.7 0.4   
        rootsift: true
        first_octave: -1
        num_octaves: 4          # 6  3
        init_blur: 1.0          # 1 2.0
        filter_kpts_with_wrapper: False
        filter_with_scale_weighting: True
        extractor_channel: grayscale
        sort_scales_low_to_large: False


    matcher:
      name: matchers.lightglue
      features: sift
      depth_confidence: -1
      width_confidence: -1
      filter_threshold: 0.1
      input_dim: 128      # if features == sift, overwwritten to 128 
      add_scale_ori: true   # if features == sift, overwwritten to true

benchmarks:
    megadepth1500:
      data:
        preprocessing:
          side: long
          resize: 1600
      eval:
        estimator: poselib
        ransac_th: 1.0
    hpatches:
      eval:
        estimator: opencv
        ransac_th: 0.5
      model:
        extractor:
          max_num_keypoints: 1024  # overwrite config above
