benchmarks:
  endopatches1800:
      data:
        num_workers: 4
        test_size: 1800
        test_seed: 0
        test_sequences: [Seq_003, Seq_016]
        test_homography_levels: [0.3, 0.5, 0.7]
        test_photometric_levels: [0.25, 0.6, 0.95]
        test_source_dir: null
        test_image_list: null
        save_dataset: False
        read_dataset_from_disk: True
        saved_dataset_dir: endopatches1800
      eval:
        estimator: poselib
        ransac_th: -1
