model:
    name: two_view_pipeline
    extractor:
      name: gluefactory_nonfree.superpoint
      max_num_keypoints: 2048
      detection_threshold: 0.0
      nms_radius: 3
    matcher:
      name: matchers.lightglue_pretrained
      features: superpoint
      depth_confidence: -1
      width_confidence: -1
      filter_threshold: 0.1
benchmarks:
    megadepth1500:
      data:
        preprocessing:
          side: long
          resize: 1600
      eval:
        estimator: opencv
        ransac_th: 0.5
    endomapper_dense1500:
      eval:
        estimator: poselib
        ransac_th: 1
    hpatches:
      eval:
        estimator: opencv
        ransac_th: 0.5
      model:
        extractor:
          max_num_keypoints: 1024  # overwrite config above
    scannet1500:
        eval:
            estimator: opencv
            ransac_th: 1.0
    endopatches1800:
          data:
            num_workers: 1
            # For generating dataset 
            test_size: 1800
            test_seed: 0
            test_sequences: [Seq_003, Seq_016]
            test_homography_levels: [0.3, 0.5, 0.7]
            test_photometric_levels: [0.25, 0.6, 0.95]
            # For generating dataset
            test_source_dir: null
            # Fallback to read images from list to generate dataset
            test_image_list: null
            save_dataset:  False
            # Read geberated dataset
            read_dataset_from_disk: True
            saved_dataset_dir: endopatches1800
          eval:
            estimator: poselib
            ransac_th: -1
          model:
            extractor:
              nms_radius: 0
